# Site settings
title: API Documentation
exclude: [ README.md, build.sh, Gemfile, Gemfile.lock, npm-debug.log, package.json ]
permalink: :categories
port: 4001

# Build settings
highlighter:    pygments
safe:           true
analytics:      UA-6765789-14
collections:
  api:
    output:     false

# Conversion
kramdown:    
  auto_ids:     false
